# Generated by Django 3.0.1 on 2019-12-27 18:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('tree_id', models.IntegerField(primary_key=True, serialize=False)),
                ('position', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
